# Generated by Django 4.0.4 on 2022-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
